mozilla-services/merino

- .circleci/check-cargo-version.sh
- Dockerfile
This should help, again, our docker build times.
> ci: Fix versions used by cargo-chef

- Cargo.lock
- config/base.yaml
- docs/ops.md
- merino-adm/Cargo.toml
- merino-adm/src/remote_settings.rs
- merino-integration-tests/Cargo.toml
- merino-integration-tests/src/suggest.rs
- merino-integration-tests/src/utils/test_tools.rs
- merino-settings/src/lib.rs
- merino-settings/src/providers.rs
- merino-web/src/suggest.rs
- merino/Cargo.toml
- merino/src/main.rs
Notably, there is no longer any attempt at all to cache data from Remote
Settings, and signatures are not verified.
Fixes #131
> refactor(adm): Remove usage of remote-settings-client

- Cargo.lock
- merino-web/Cargo.toml
- merino-web/src/endpoints/dockerflow.rs
- merino-web/src/endpoints/providers.rs
- merino-web/src/endpoints/suggest.rs
- merino-web/src/errors.rs
- merino-web/src/extractors.rs
- merino-web/src/middleware/metrics.rs
- merino-web/src/middleware/sentry.rs
- merino-web/src/suggest.rs
Since the `err.backtrace()` is still unstable in Rust, this uses the same approach as [Contile via the Backtrace crate](https://github.com/mozilla-services/contile/issues/158).
Fixes #139 
Here's a [submitted sample error](https://sentry.prod.mozaws.net/operations/merino-local/issues/13572769/?query=is%3Aunresolved).
**Note**: This is identical to #152. Due to problems on CI I'm trying to make it work by recreating the PR.
> feat: Report stacktraces for errors to Sentry

- .cargo/audit.toml
This is a follow-up that should make CI work again. Given that the advisory does not recommend any particular strategy, I propose to suppress this exception and create an issue to update chrono once it becomes available.
> devel: add a rustsec exception for chrono to unblock CI

- .github/CODEOWNERS
I renamed the GitHub team name for test engineering to be more consistent with the Jira label and the parent team's name.
> chore: update GitHub team name in Code Owners file

- docs/data.md
- merino-integration-tests/src/caching/redis_tests.rs
- merino-integration-tests/src/suggest.rs
- merino-integration-tests/src/utils/logging.rs
- merino-suggest/src/domain.rs
- merino-suggest/src/lib.rs
- merino-web/src/endpoints/suggest.rs
- test: make LogWatcher::has #[must_use], and fix a misuse of it
- fix: log sugestion request data with proper MozLog type information
Fixes #196
> fix: log sugestion request data with proper MozLog type information

- docs/data.md
- merino-cache/src/memory.rs
- merino-cache/src/redis/mod.rs
**Note: this is based on #205 and will need to be rebased after that gets merged.**
This additionally adds a metric to track the number of items in the in-memory cache. Note that this does not add the same count of items for the Redis cache, as it's slightly more involved there and I'd take it as a separate, specific PR.
This contributes toward #207 , but follow-up work is required to fix it.
> feat: instrument cache hit and misses

- merino-adm/src/remote_settings/mod.rs
Notably, this algorithm never suggests more than the rest of the current word.
Fixes #213
> fix(adm): Use Firefox's full_keyword algorithm

- merino-web/src/endpoints/suggest.rs
Discovered this while investigating nonprod logging in scope of
https://mozilla-hub.atlassian.net/browse/SVCSE-138
> form_factor field name typo in logs

- merino-adm/src/remote_settings/mod.rs
This fixes #242.
Those suggestions, reported in #242, all have a wide range of targeting keywords, e.g
```
[
"cars eb",
"cars eba",
"cars ebay"
"eb",
"eba",
"ebay",
...
]
``` 
Hence, we need to filter out those keywords that don't share the same prefix with the search query (e.g. "eb") when trying to extract the full keyword.
> fix(adm): Filter keywords that do not start with the partial query

- config/test.yaml
- merino-adm/src/remote_settings/mod.rs
The default value that remote-settings-client uses for the server includes the /v1 suffix, but ours doesn't. Add it back in so that we don't confuse the client.
> fix(adm): Include `/v1` on the end of the remote settings URL we give to the RS client

- merino-adm/src/remote_settings/mod.rs
- merino-adm/src/remote_settings/reqwest_client.rs
This fixes #259.
The issue was caused by the connection pool in Reqwest/Hyper. See more details in [here](https://github.com/hyperium/hyper/issues/2136#issuecomment-589345238).
Since `ReqwestClient` is only used by RS suggester, and it is not making constant network calls to RS. Disabling the connection pool should not be a big deal, but I will let @mythmon @Dexterp37 decide if this is acceptable or shall we keep it as is and add the retry to the API.
> test: Fix intermittent failures with ReqwestClient

- config/ci.yaml
- test-engineering/contract-tests/client/tests/conftest.py
- test-engineering/contract-tests/client/tests/models.py
- test-engineering/contract-tests/client/tests/test_merino.py
- test-engineering/contract-tests/docker-compose.yml
- test-engineering/contract-tests/volumes/client/scenarios.yml
- test-engineering/load-tests/docker-compose.yml
This is currently failing locally for me as Merino does not return any suggestions from the RS provider. 🚧 
The tests passed prior to rebasing my changes to the current upstream `main` branch, which included commits for switching to the `remote-settings-client` crate from our custom client implementation:
* #232 
I don't know what the source of this error is yet. It may be worth reverting the client integration and see if the tests then pass to verify that this is indeed caused by the other client.
Please see the thread on Slack for additional context.
Resolve #143
> Add contract tests for RS provider

- .circleci/config.yml
> ci: Split pr, main, and tag workflows to be more explicit about publishing

- Cargo.lock
- merino-adm/Cargo.toml
- merino-adm/src/remote_settings/mod.rs
- merino-adm/src/remote_settings/soft_verifier.rs
this implements a new signature verifier that performs the signature verification on content coming from remote settings
but exclusively logs errors, still allowing to use any oddly signed content.
Note: you can already verify that this is correctly working since tests don't specify the proper x5u field and so verification is failing (and printing a log).
Fixes #218
Fixes #264
> feat: check signature of remote-settings content

- docs/ops.md
- merino-cache/src/memory.rs
> fix(cache): Respect the max_removed_entry configuration

- .circleci/config.yml
- merino-cache/src/memory.rs
This makes the function a bit easier to reason about, and requires less special case comments and cloning.
> refactor(memory-cache): Make the background expiry task a selfish method by adding more Arcs

- merino-cache/Cargo.toml
- merino-cache/src/memory.rs
While Merino uses the "max-removal-entries" to throttle the cache expiry job, it will still prevent other tasks, scheduled on the same thread, from running because those lock acquisitions of the underlying cache stores are inherently blocking. As a result, it might increase the response latency for those affected requests.
Cache cleanup is not of the highest priority and can be done in the background, offloading the expiry task to the blocking threads of the runtime could help smooth those latency spikes.
> refactor(memory-cache): Offload the cache expiry task to the blocking threads

- Cargo.lock
- merino-suggest/Cargo.toml
- merino-suggest/src/lib.rs
- merino-web/Cargo.toml
- merino-web/src/endpoints/suggest.rs
- merino-web/src/errors.rs
- merino-web/src/extractors.rs
- merino-web/src/middleware/metrics.rs
- merino-web/src/middleware/sentry.rs
- merino/Cargo.toml
Replaces our home-grown `Accept-Language` parsing logic with Actix Web's, closing #90. I didn't want to introduce Actix Web as a depedency of `merino-suggest`, but I couldn't think of a better way to use the necessary types (`QualityItem`, `Preference`, etc.). Re-exporting them from the `merino-web` crate would require `merino-suggest` to add `merino-web` as a dependency, which creates a cyclic dependency.
> refactor: use actix-web to parse Accept-Language header

- Cargo.lock
- merino-suggest/Cargo.toml
- merino-web/Cargo.toml
- merino/Cargo.toml
refactor(web): Disable compression related features in actix-web
Nginx handles compression for us, and these features (especially zstd) add
significant compile time. On my machine a clean release compilation went from
90 seconds with zstd to 65 seconds without.
> Remove compression features from actix-web

- Cargo.lock
- config/base.yaml
- config/ci.yaml
- config/development.yaml
- config/production.yaml
- config/providers/base.yaml
- config/providers/ci.yaml
- config/providers/development.yaml
- config/providers/production.yaml
- config/providers/test.yaml
- config/test.yaml
- docs/ops.md
- merino-settings/Cargo.toml
- merino-settings/src/lib.rs
- merino-settings/src/logging.rs
- merino-settings/src/providers.rs
- merino-web/src/lib.rs
- merino/src/main.rs
- test-engineering/contract-tests/docker-compose.yml
- test-engineering/load-tests/docker-compose.yml
This fixes #293 
Change highlights:
* Moved the configurations for suggestion provider to its own settings
* Added a new helper struct `SuggestionProviderSettings` to load settings. My understanding is that we can build up the dynamic loading around it later.   
Notes:
* This requires a change to `cloudops-infra`       
* The configuration sources for providers and the overriding rules are identical to the top-level settings. I am open to further simplifying that if necessary
* The top-level `Settings` still hold the `suggestion_providers` as I don't see much benefit of spitting it from the `Settings` for now.
> refactor(settings): Split suggestion provider configuration from main settings

- Cargo.lock
- Cargo.toml
- config/base.yaml
- dev/docker-compose.yaml
- merino-settings/src/lib.rs
- merino-wikipedia/Cargo.toml
- merino-wikipedia/src/demo.rs
- merino-wikipedia/src/domain.rs
- merino-wikipedia/src/es_helper.rs
- merino-wikipedia/src/lib.rs
Consider using `cargo run --bin elasticsearch-demo` to test indexing a simple document into ES.
> feat(wikipedia): Add basic data model to index Wikipedia into Elasticsearch

- Cargo.lock
- docs/data.md
- docs/ops.md
- merino-integration-tests/src/suggest.rs
- merino-web/src/endpoints/suggest.rs
See https://mozilla-hub.atlassian.net/browse/SVCSE-241
The design for this particular field was proposed and accepted in the
[Add "sensitive" field for log routing](https://docs.google.com/document/d/1WI5XotvZoUNaw3sQQfQtn8C7RBv1wKmFiYpvd7yobh8/edit#)
decision doc.
> SVCSE-241 Add "sensitive" flag to web.suggest.request log messages

- merino-cache/src/redis/mod.rs
- merino-integration-tests/src/caching/redis_tests.rs
- merino-integration-tests/src/utils/test_tools.rs
This fixed [CONSVC-1618](https://mozilla-hub.atlassian.net/browse/CONSVC-1618).
The reconfigure for Redis provider was already implemented in #337, this added an integration for it.
> test: add an integration test for redis reconfigure

- .circleci/config.yml
- docs/SUMMARY.md
- docs/dev/release-process.md
Fixes #339.
This introduces a mechanism to tag the latest commit in the PR in order to prevent deploying it to stage/prod.
In addition to that, it removes the deprecated release-tagging mechanism (we're now always deploying to stage, so we don't need to tag releases to do that) and documents the current release practices.
I added CI to a sample repo in my account, and here's how it works: [example](https://app.circleci.com/pipelines/github/Dexterp37/test_ci/17/workflows/ffddcb61-259a-4589-ad0f-0b243481b326/jobs/28)
> feat: provide a mechanism to prevent deploying

- .circleci/config.yml
- docs/dev/release-process.md
This introduces the CircleCI facilities that are used to trigger deployment to production.
It also changes the release process documents to highlight the new release process.
Here's what the UI looks like (I tried this in my [toy repo](https://github.com/Dexterp37/test_ci)):
Works toward, but does not fully fix, #352 (it still lacks the SRE changes on the pipeline side).
> consvc-1670 - Enable deploying to production

- .github/dependabot.yml
Dependency updates for `merino-showroom` do not need a deployment.
> chore: add do-not-deploy for dependabot commit messages

- Cargo.lock
- merino-adm/Cargo.toml
- merino-settings/Cargo.toml
- merino-settings/src/lib.rs
- merino-web/Cargo.toml
- merino/Cargo.toml
Lots of security alerts with the old sentry clients, I guess we're now good to use the latest one.
> chore: Update sentry to the latest

- .circleci/config.yml
This fixes [CONSVC-1779](https://mozilla-hub.atlassian.net/browse/CONSVC-1779).
Turns out that `circle-agent step halt` works at the job level rather than at the workflow level, that's why CircleCI still processes the subsequent jobs. Per this [thread](https://discuss.circleci.com/t/does-circleci-step-halt-works-with-version-2-1/36674/2), we have to cancel the entire workflow which I think it's reasonable in our case.
cc: @hackebrot
> chore: Skip circleci approval task for do-not-deploy tags [do not deploy]

- merino-adm/src/remote_settings/reqwest_client.rs
as remote_settings_client::client::net::ViaductClient does
Issue #383
> fix: request_json should default to a json content-type

- merino-cache/src/redis/domain.rs
- merino-settings/src/logging.rs
- merino-suggest-traits/src/device_info.rs
- merino-suggest-traits/src/lib.rs
- test-engineering/contract-tests/client/README.md
- test-engineering/contract-tests/client/tests/models.py
- test-engineering/contract-tests/client/tests/test_merino.py
WIP
I followed the spec in the Pydantic docs [here](https://pydantic-docs.helpmanual.io/usage/models/#required-fields) and while there are some other ways to go about handing these optional fields, it can be can discussed them further based on your thoughts @Trinaa. I see the use of `default_factory` a few times which we could make use of given the hope of breaking up Merino and Kinto requests.  
I also saw something like this could work, however we don't want it to occur for each run of the test, but I wanted to point it out as an option nonetheless:
`@pytest.fixture(autouse=True)
def slow_down_tests():
yield
time.sleep(1)`
Post discussion and walking through both changes in our separate branches, we can move out of WIP status.
> added request delay field with default and implementation in test_merino [do not deploy]

- .circleci/config.yml
- Dockerfile
switching from the deprecated ci-docker-bases to cimg
and pin the rust version in ci, matching the Dockerfile
Closes #355
> chore: update to the latest rust [do not deploy]

- test-engineering/contract-tests/client/README.md
- test-engineering/contract-tests/client/tests/kinto.py
- test-engineering/contract-tests/client/tests/test_merino.py
- test-engineering/contract-tests/volumes/client/scenarios.yml
* add teardown fixture in merino contract tests
* add delete records function to kinto module
* increase delay in contract test scenarios to assure remote settings resync in merino
* update README
⚠️ **Note**: These changes are identical to https://github.com/mozilla-services/merino-py/pull/43
[CONSVC-1840](https://mozilla-hub.atlassian.net/browse/CONSVC-1840)
> test: clear records between scenario executions in contract tests [do not deploy]

- config/base.yaml
- docs/ops.md
- merino-adm/src/remote_settings/mod.rs
- merino-adm/src/remote_settings/reqwest_client.rs
- merino-settings/src/lib.rs
- test-engineering/contract-tests/docker-compose.yml
This makes the HTTP timeout configurable for `ReqwestClient` (the underlying client of Remote Settings). It allows us to fix the timeout issue that we're experiencing in docker on Apple M1 laptops.
This fixes [CONSVC-1894](https://mozilla-hub.atlassian.net/browse/CONSVC-1894).
> feat: Add a timeout configuration for Remote Settings
