mozilla-services/merino

- merino-settings/src/lib.rs
- merino/src/sentry.rs
> feat: Add setting to configure sentry env

- config/base.yaml
- config/test.yaml
- merino-integration-tests/src/utils/test_tools.rs
- merino-settings/src/lib.rs
- merino/src/main.rs
This fixes [this JIRA ticket](https://mozilla-hub.atlassian.net/browse/CONSVC-1263).
Fixes #137
> feat: make metrics sink address support hostnames

- Cargo.lock
- docs/ops.md
- merino-cache/src/redis/mod.rs
- merino-settings/src/providers.rs
- merino-suggest/Cargo.toml
- merino-suggest/src/lib.rs
- merino-suggest/src/timeout.rs
- merino-web/src/suggest.rs
- test(cache): Make memory locking test failures easier to read
- feat(suggest): Add timeout provider
Fixes #55
> feat(suggest): Add timeout provider

- config/development.yaml
- config/test.yaml
- docs/dev/index.md
- docs/ops.md
- merino-settings/src/lib.rs
This should help testing things with Sentry.
> dev: Add server debug mode for Sentry

- README.md
- book.toml
- dev/make-all-docs.sh
- docs/dev/index.md
> docs: Make getting to the docs easier

- .circleci/config.yml
- .dockerignore
- .gitignore
- Dockerfile
- test-engineering/docker-compose.yml
This is basically the same thing as #163, but I want to leave that one in place for others to review my steps. This PR should improve our CI. Although it doesn't fix our caching problem, I think it is worth reviewing and merging as is.
> ci: Better organize Docker stages for improved cache debugging

- Cargo.lock
- merino-web/Cargo.toml
- merino/Cargo.toml
> chore: use tracing-actix-web-mozlog 0.3.1

- docs/SUMMARY.md
- docs/data.md
- docs/dev/index.md
- docs/dev/logging-and-metrics.md
> doc: Document metrics and logging policies and existing collection

- merino-suggest/Cargo.toml
- merino-suggest/src/providers/id_multi.rs
- merino-suggest/src/providers/multi.rs
> test(suggest): Add tests to verify Multi and IdMulti run providers concurrently

- merino-integration-tests/src/caching/redis_tests.rs
> test: Fix flaky bad_cache_data_is_handled test

- CHANGELOG.md
- Cargo.lock
- deduped-dashmap/Cargo.toml
- merino-adm/Cargo.toml
- merino-cache/Cargo.toml
- merino-integration-tests-macro/Cargo.toml
- merino-integration-tests/Cargo.toml
- merino-settings/Cargo.toml
- merino-suggest/Cargo.toml
- merino-web/Cargo.toml
- merino/Cargo.toml
> chore: tag 0.4.0

- .github/ISSUE_TEMPLATE/release-template.md
> Add --from-latest-tag to clog command template

- .circleci/config.yml
- Cargo.lock
- config/base.yaml
- config/test.yaml
- dev/.kinto-attachments/.gitignore
- dev/docker-compose.yaml
- dev/kinto.ini
- docs/ops.md
- merino-adm/src/remote_settings/client.rs
- merino-adm/src/remote_settings/mod.rs
- merino-integration-tests/Cargo.toml
- merino-integration-tests/src/utils/test_tools.rs
- merino-settings/src/lib.rs
- merino-settings/src/providers.rs
- dev: Add a kinto server to the dev docker-compose
- test: Use a real kinto server for tests
> Kinto in Docker Compose

- merino-integration-tests/src/utils/test_tools.rs
This fixes #224.
I am still not entirely sure about the cause of the test failures, so I ended up working around it by adding a retry mechanism to all the RS setup code paths. It seemed to work fine locally. Anyway, let's make CI green first.
> test: Fix intermittent RS setup failures

- merino-web/src/endpoints/suggest.rs
Notably, this does *not* record a literal `null` for the locations. Instead the fields are elided entirely.This is not optimal, but was also the best solution I've found so far.
Fixes #230.
> fix(logs): don't record a value for missing location in logs

- .circleci/config.yml
- CHANGELOG.md
- Cargo.lock
- deduped-dashmap/Cargo.toml
- merino-adm/Cargo.toml
- merino-cache/Cargo.toml
- merino-integration-tests-macro/Cargo.toml
- merino-integration-tests/Cargo.toml
- merino-integration-tests/src/utils/test_tools.rs
- merino-settings/Cargo.toml
- merino-suggest/Cargo.toml
- merino-web/Cargo.toml
- merino/Cargo.toml
> chore: tag 0.4.2

- test-engineering/contract-tests/README.md
This pull request updates the README for the contract tests to use the correct terminology.
> docs: fix contract tests README.md

- dev/docker-compose.yaml
This should fix out CI problems as of late.
Fixes #250
> ci: Pin version of kinto-dist

- CHANGELOG.md
- Cargo.lock
- deduped-dashmap/Cargo.toml
- merino-adm/Cargo.toml
- merino-cache/Cargo.toml
- merino-integration-tests-macro/Cargo.toml
- merino-integration-tests/Cargo.toml
- merino-settings/Cargo.toml
- merino-suggest/Cargo.toml
- merino-web/Cargo.toml
- merino/Cargo.toml
> chore: tag 0.4.3

- CHANGELOG.md
- Cargo.lock
- deduped-dashmap/Cargo.toml
- merino-adm/Cargo.toml
- merino-cache/Cargo.toml
- merino-integration-tests-macro/Cargo.toml
- merino-integration-tests/Cargo.toml
- merino-settings/Cargo.toml
- merino-suggest/Cargo.toml
- merino-web/Cargo.toml
- merino/Cargo.toml
> chore: tag 0.4.4

- merino-adm/src/remote_settings/reqwest_client.rs
> feat: don't hide inner errors in the log message

- CHANGELOG.md
- Cargo.lock
- deduped-dashmap/Cargo.toml
- merino-adm/Cargo.toml
- merino-cache/Cargo.toml
- merino-integration-tests-macro/Cargo.toml
- merino-integration-tests/Cargo.toml
- merino-settings/Cargo.toml
- merino-suggest/Cargo.toml
- merino-web/Cargo.toml
- merino/Cargo.toml
> chore: tag 0.5.0

- deduped-dashmap/src/lib.rs
This was likely causing #289, since it causes some storage entries to continue
being stored past when their last pointer was removed, due to the reference
count not being updated correctly.
The result of this is that storage entries would leak if their last pointer was
removed via `::remove` instead of via `::retain`.
> fix(deduped-map): Correctly remove pointer and storage entries when calling DedupedMap::remove

- CHANGELOG.md
- Cargo.lock
- deduped-dashmap/Cargo.toml
- merino-adm/Cargo.toml
- merino-cache/Cargo.toml
- merino-integration-tests-macro/Cargo.toml
- merino-integration-tests/Cargo.toml
- merino-settings/Cargo.toml
- merino-suggest/Cargo.toml
- merino-web/Cargo.toml
- merino/Cargo.toml
> chore: tag 0.5.1

- merino-integration-tests/src/utils/redis.rs
- merino-suggest-traits/src/device_info.rs
- merino-suggest-traits/src/lib.rs
This will unblock the landing of other pending PRs.
> chore: Fix Clippy warnings

- docs/ops.md
> docs: update to new merino-local project url

- Cargo.lock
- merino-adm/Cargo.toml
- merino-adm/src/remote_settings/reqwest_client.rs
- merino-adm/src/remote_settings/soft_verifier.rs
including a fix for our intermittent contract test failures
Closes #383
> fix: update to the latest remote-settings-client

- config/providers/ci.yaml
- test-engineering/contract-tests/volumes/client/scenarios.yml
- test-engineering/contract-tests/volumes/kinto/data-03.json
- test-engineering/contract-tests/volumes/kinto/data-04.json
* add test scenario for remote settings refresh
⚠️ **Note**: These changes should be identical to https://github.com/mozilla-services/merino-py/pull/48
[CONSVC-1866](https://mozilla-hub.atlassian.net/browse/CONSVC-1866)
> test: add contract tests for remote settings refresh [do not deploy]
